# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publisher

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *' # JST 6:00

env:
  SID: ${{ secrets.SID }}
  SOURCE_PROJECT_NAME: ${{ secrets.SOURCE_PROJECT_NAME }}
  DESTINATION_PROJECT_NAME: ${{ secrets.DESTINATION_PROJECT_NAME }}

jobs:
  publisher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Restore last_import.txt
        uses: actions/cache@v4
        with:
          path: last_import.txt
          key: last-import-time

      - name: Run publisher
        run: bun run src/index.ts
